version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: tienda-celulares-api
    # restart: always
    environment:
      POSTGRES_DB: tienda-celulares-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: "UTC-4"
    ports:
      - 3232:3232
    command: -p 3232

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: tienda-celulares-pgadmin
    # restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 4242
    ports:
      - 4242:4242
    depends_on:
      - postgres
